homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 1.339300
  longitude: 103.845493
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Singapore
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: Sayonara!1
  # ssl_certificate: /home/homeassistant/.homeassistant/certificate.pem
  # ssl_key: /home/homeassistant/.homeassistant/privkey.pem
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
#sensor:
#  - platform: yr

sensor:
  - platform: mqtt
    state_topic: 'IoTSensor/Sensors'
    name: 'SGHome_Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: 'IoTSensor/Sensors'
    name: 'SGHome_Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
#  - platform: mqtt
#    state_topic: "owntracks/mysticrenji/huawei"
#    name: "Battery - Huawei"
#    unit_of_measurement: "%"
#    value_template: '{{ value_json.batt }}'

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
#automation: !include automations.yaml
script: !include scripts.yaml

mqtt:
  broker: a1nXXXXXX.iot.us-west-2.amazonaws.com
  port: 8883
  client_id: home-assistant
  certificate: /home/pi/IOT/AWSIoT/root-CA.crt
  client_key:  /home/pi/IOT/AWSIoT/IoTSensor.private.key
  client_cert: /home/pi/IOT/AWSIoT/IoTSensor.cert.pem

camera:
  - platform: mqtt
    topic: IoTSensor/Data
    name: "Remote Device"





